(base) ]0;~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[01;34m~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[00m$ conda e[Kwebsite

CommandNotFoundError: No command 'conda website'.

(base) ]0;~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[01;34m~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[00m$ conda activate website
(website) ]0;~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[01;34m~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[00m$ main.py
bash: main.py: command not found
(website) ]0;~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[01;34m~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[00m$ python main.py
python: can't open file 'main.py': [Errno 2] No such file or directory
(website) ]0;~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[01;34m~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[00m$ cd..
bash: cd..: command not found
(website) ]0;~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[01;34m~/Group Notebooks and Projects/GPT/our_NLP_website/app/templates[00m$ cd ..
(website) ]0;~/Group Notebooks and Projects/GPT/our_NLP_website/app[01;34m~/Group Notebooks and Projects/GPT/our_NLP_website/app[00m$ python main.[K.py
/projects/84aea4b7-0c8e-42b9-8987-a9a9da55cd36/miniconda3/envs/website/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  rank_zero_deprecation(
Try to open

    https://cocalcx.ai-camp.org/84aea4b7-0c8e-42b9-8987-a9a9da55cd36/port/12345/


 * Serving Flask app 'main' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    app.run(host = '0.0.0.0', port=port, debug=True)
  File "/projects/84aea4b7-0c8e-42b9-8987-a9a9da55cd36/miniconda3/envs/website/lib/python3.8/site-packages/flask/app.py", line 922, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "/projects/84aea4b7-0c8e-42b9-8987-a9a9da55cd36/miniconda3/envs/website/lib/python3.8/site-packages/werkzeug/serving.py", line 982, in run_simple
    s.bind(server_address)
OSError: [Errno 98] Address already in use
(website) ]0;~/Group Notebooks and Projects/GPT/our_NLP_website/app[01;34m~/Group Notebooks and Projects/GPT/our_NLP_website/app[00m$ 